completo = input("Escribe tu Nombre Completo: ")
minusculas = completo.lower()
mayusculas = completo.upper() 
formateado = completo.title()
print("\nNombre completo en minúsculas:", minusculas)
print("Nombre completo en mayúsculas:", mayusculas)
print("Nombre completo formateado:", formateado)